name: mobile_coverage

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string

jobs:
  coverage:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run == 'true' }}
    name: coverage
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    container:
      image: envoyproxy/envoy-build-ubuntu:818d28832abf2a7c0cb2bff00435be231729a0bf
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run coverage'
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && BAZEL_BUILD_OPTION_LIST="--config=remote-ci-linux-coverage" \
            PATH=/opt/llvm/bin:${PATH} \
            COVERAGE_THRESHOLD=95 \
            ../test/run_envoy_bazel_coverage.sh //test/common/...
    - name: 'Package coverage'
      run: |
        cd mobile && tar -czvf coverage.tar.gz generated/coverage
    - name: 'Upload report'
      uses: actions/upload-artifact@v3
      with:
        name: coverage.tar.gz
        path: coverage.tar.gz
